[jenkins_master]
13.38.163.61 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/dittopedia_jenkins_key.pem

[jenkins_worker]
jenkins-worker ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/dittopedia_jenkins_key.pem
